### ISSUE TITLE
Unable to create new test template

### ISSUE THREAD

**Issue by settur1409** [OpenIxia/bps_restpy#2]
Hello,
         I am below sequence of APIs to create a new test template. But I am getting 404 error. 

print("logging into BPS")
bps = BPS(bps_system, bpsuser, bpspass)
bps.login()

print("Creating new test")
bps.testmodel.new("Test1") --> not working

Below is the error message that, I am getting:
_"Exception: {'status_code': 400, 'content': 'ErrorException: Invalid test name "Test1"..  Execute: help(<BPS session name>.testmodel.new) for more information about the method.'}"_

I am able to perform this action on existing test templates.
Ex: bps.testmodel.new("AppSim")  --> is working

Kindly help me if I am missing something.

**Comment by nutu** [comment]
Hi,

**Comment by nutu** [comment]
> Hello,
> I am below sequence of APIs to create a new test template. But I am getting 404 error.
> 
> print("logging into BPS")
> bps = BPS(bps_system, bpsuser, bpspass)
> bps.login()
> 
> print("Creating new test")
> bps.testmodel.new("Test1") --> not working
> 
> Below is the error message that, I am getting:
> _"Exception: {'status_code': 400, 'content': 'ErrorException: Invalid test name "Test1".. Execute: help(.testmodel.new) for more information about the method.'}"_
> 
> I am able to perform this action on existing test templates.
> Ex: bps.testmodel.new("AppSim") --> is working
> 
> Kindly help me if I am missing something.

This is a bit confusing but :  The bps.testmodel.new should be called without arguments. Ex: **bps.testmodel.new()**.  
We mentioned this but is easily overlooked:
```
help(bps.testmodel.new)
Help on method new in module bps_restpy.restPyWrapper:

new(self, template=None) method of bps_restpy.restPyWrapper.DataModelProxy instance
    Creates a new Test Model
    :param template (string): The name of the template. In this case will be empty.
```

This will create a new model that can be saved on the bps system:  
`bps.testmodel.saveAs("The_New_Test1",force= True)`


As a note, to load a previously created testmodel for modifying it the following method should be used:
`bps.testmodel.load('AppSim')`
